#pragma once
#define KNIGHT_IDLE_FILE "./assets/img/knight 3 idle.png"

#define KNIGHT_IDLE_FILE_FRAME_1_UX 
#define KNIGHT_IDLE_FILE_FRAME_1_UY 
#define KNIGHT_IDLE_FILE_FRAME_1_DX 
#define KNIGHT_IDLE_FILE_FRAME_1_DY 

#define KNIGHT_IDLE_FILE_FRAME_2_UX 
#define KNIGHT_IDLE_FILE_FRAME_2_UY 
#define KNIGHT_IDLE_FILE_FRAME_2_DX 
#define KNIGHT_IDLE_FILE_FRAME_2_DY 

#define KNIGHT_IDLE_FILE_FRAME_3_UX 
#define KNIGHT_IDLE_FILE_FRAME_3_UY 
#define KNIGHT_IDLE_FILE_FRAME_3_DX 
#define KNIGHT_IDLE_FILE_FRAME_3_DY 

#define KNIGHT_IDLE_FILE_FRAME_4_UX 
#define KNIGHT_IDLE_FILE_FRAME_4_UY 
#define KNIGHT_IDLE_FILE_FRAME_4_DX 
#define KNIGHT_IDLE_FILE_FRAME_4_DY 
